# Website specifications
title: "SSCAD 2026" # Website's name
description: XXVII Simp√≥sio em Sistemas Computacionais de Alto Desempenho (SSCAD 2026) da SBC
url: "https://sscad26.imd.ufrn.br" 
baseurl: "/" # Website's subpath (e.g.: /blog)
final_url: https://sscad26.imd.ufrn.br/
source_url: "https://github.com/NPAD-UFRN/sscad2026" 
encoding: UTF-8

# Website collections
collections_dir: collections
collections:
  news:
  keynote_speakers:
    sort_by: order

# Website SASS settings
sass:
  sass_dir: _sass
  style: compressed

# Jekyll plugins
plugins:
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - docker-compose.yml
  - .github
  - .gitignore
  - .devcontainer
  - .vscode
  - .dockerignore
  - vendor
