version: '3.8'
services:
  sscad:
    image: docker.io/jekyll/jekyll
    container_name: sscad
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - sscad_gems:/usr/local/bundle
    environment:
      - JEKYLL_ROOTLESS=1
    command: jekyll serve

volumes:
  sscad_gems:
    name: sscad_gems
